#!/usr/bin/env bash
# configures new server
apt-get update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.backup
echo "Hello Holberton School this server is coooool!" > /usr/share/nginx/html/index.html
service nginx restart
