#!/usr/bin/env bash
# configures new server with redirect and nginx
apt-get update
apt-get -y install nginx
redirect="root /var/www/html;\n\n\tlocation /redirect_me {\n\t\treturn\t301 https://www.holbertonschool.com/;\n\t}\n\n"
mkdir -p 'var/www/html'
echo "Holberton School" > '/var/www/html/index.html'
sed -i "s,root \/var\/www\/html;,$redirect," /etc/nginx/sites-enaabled/default
service nginx restart
