#!/usr/bin/env bash
#set up a server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "19i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart