#!/usr/bin/env bash
#Set up load balancer
echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | \
    tee /etc/apt/sources.list.d/backports.list
apt-get update
apt-get install -y haproxy -t trusty-backports
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sed -i "6 i \\\nENABLED=1\n" /etc/default/haproxy
sed -i "\$a\
listen backend *:80\n\
\tmode http\n\tbalance roundrobin\n\
\tserver 720-web-01 35.196.61.182 check\n\
\tserver 720-web-02 35.231.189.24 check\n" \
    /etc/haproxy/haproxy.cfg
sudo service haproxy start
